# Generated by Django 3.1.2 on 2022-09-21 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0024_auto_20220408_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
